name: GitHub Actions Build
on:
  # Trigger the workflow on push or pull request,
  # but only for the main branch
  push:
    branches: ["main", "05-trend-ci", "07-trend-semver"]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2 # If you're using actions/checkout@v2 you must set persist-credentials to false in most cases for the deployment to work correctly.
        with:
          persist-credentials: false
      - name: Install and Build
        run: |
          npm install
          npm run validate
      - name: Semantic Release
        uses: cycjimmy/semantic-release-action@v2
        with:
      # You can specify specifying version range for the extra plugins if you prefer.
        extra_plugins: |
          @semantic-release/commit-analyzer
          @semantic-release/release-notes-generator
          @semantic-release/npm
          @semantic-release/github
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
