name: GitHub Actions Build
on:
  # Trigger the workflow on push or pull request,
  # but only for the main branch
  push:
    branches: ["main", "05-trend-ci"]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2 # If you're using actions/checkout@v2 you must set persist-credentials to false in most cases for the deployment to work correctly.
        with:
          persist-credentials: false
      - name: Install and Build
        run: |
          npm install
          npm run validate
